### ISSUE TITLE
Support File Based Encryption

### ISSUE THREAD

**Issue by no-identd** [omnirom/android_device_huawei_angler#1]
See here:

https://github.com/TeamWin/android_device_huawei_angler/issues/6

**Comment by no-identd** [comment]
And here:
https://github.com/omnirom/android_kernel_huawei_angler/issues/1

**Comment by Entropy512** [comment]
http://jira.omnirom.org/ - while I'm retired from development, I am 99% certain that Omni still does not track issues on github or accept pull requests from github, as has been the case since the beginning.

**Comment by no-identd** [comment]
Okay. Just a suggestion then: You might want to consider disabling issues on the repositories then (Github has an option for that), or using something like https://github.com/coreos/issue-sync.

Also, unfortunately the Omnirom JIRA environment doesn't support HTTPS... :|

**Comment by no-identd** [comment]
See https://github.com/TeamWin/Team-Win-Recovery-Project/issues/854
